# Generated by Django 5.2.1 on 2025-09-21 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('education', models.CharField(max_length=200)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.TextField(help_text='List your key skills, separated by commas')),
                ('experience', models.TextField(blank=True, help_text='Mention work experience or write Fresher', null=True)),
                ('about_you', models.TextField(blank=True, help_text='Briefly describe yourself, your interests and goals', null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('mode', models.CharField(blank=True, choices=[('hr', 'HR'), ('technical', 'Technical'), ('gd', 'Group Discussion')], max_length=20, null=True)),
                ('time_per_question', models.IntegerField(default=60, help_text='Time in seconds (default 60s, max 180s)')),
                ('num_questions', models.IntegerField(choices=[(5, '5'), (10, '10'), (20, '20')], default=5)),
                ('custom_keywords', models.TextField(blank=True, help_text='Optional: Keywords for AI (e.g. DSA, DBMS, Communication)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
