# Generated by Django 5.2.1 on 2025-09-22 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('language', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('spanish', 'Spanish'), ('french', 'French'), ('other', 'Other')], default='english', max_length=20)),
                ('language_proficiency', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('pro', 'Proficient')], default='basic', max_length=20)),
                ('mode', models.CharField(choices=[('basic_intro', 'Basic Intro (Self Introduction, Simple Conversation)'), ('intermediate', 'Intermediate (Group Discussions, Peer Conversations)'), ('pro', 'Pro Level (Professional Scenario Roleplay)')], default='basic_intro', max_length=20)),
                ('reason', models.CharField(choices=[('office', 'Office / Workplace Communication'), ('travel', 'Travel / Tour Communication'), ('students', 'Classroom / Student Interaction'), ('presentation', 'Presentations / Public Speaking'), ('personal', 'Personal Growth / Confidence'), ('custom', 'Other (User defined)')], default='personal', max_length=50)),
                ('custom_reason', models.CharField(blank=True, help_text="If you select 'Other', write your reason here", max_length=200, null=True)),
                ('time_per_round', models.IntegerField(default=60, help_text='Time in seconds (default 60s, max 180s)')),
                ('num_rounds', models.IntegerField(choices=[(3, '3'), (4, '4'), (5, '5')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PresentationPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppt_file', models.FileField(blank=True, null=True, upload_to='presentations/')),
                ('topic_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Write about your topic', null=True)),
                ('audience_type', models.CharField(choices=[('employees', 'Employees'), ('students', 'Students'), ('teachers', 'Teachers'), ('general', 'General Audience')], default='general', max_length=20)),
                ('time_per_question', models.IntegerField(default=60, help_text='Time in seconds (default 60s, max 180s)')),
                ('num_questions', models.IntegerField(choices=[(5, '5'), (10, '10'), (15, '15'), (20, '20')], default=5)),
                ('custom_keywords', models.TextField(blank=True, help_text='Optional: Keywords for AI (e.g. Confidence, Body Language, Communication)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
