# Generated by Django 5.2 on 2025-10-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customquestion',
            name='question_set',
        ),
        migrations.RemoveField(
            model_name='customquestionset',
            name='user',
        ),
        migrations.RemoveField(
            model_name='interviewdetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='presentationpractice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommunicationPractice',
        ),
        migrations.DeleteModel(
            name='CustomQuestion',
        ),
        migrations.DeleteModel(
            name='CustomQuestionSet',
        ),
        migrations.DeleteModel(
            name='InterviewDetails',
        ),
        migrations.DeleteModel(
            name='PresentationPractice',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
