# Generated by Django 5.2.1 on 2025-10-04 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('language', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('spanish', 'Spanish'), ('french', 'French'), ('other', 'Other')], default='english', max_length=20)),
                ('language_proficiency', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('pro', 'Proficient')], default='basic', max_length=20)),
                ('mode', models.CharField(choices=[('basic_intro', 'Basic Intro (Self Introduction, Simple Conversation)'), ('intermediate', 'Intermediate (Group Discussions, Peer Conversations)'), ('pro', 'Pro Level (Professional Scenario Roleplay)')], default='basic_intro', max_length=20)),
                ('reason', models.CharField(choices=[('office', 'Office / Workplace Communication'), ('travel', 'Travel / Tour Communication'), ('students', 'Classroom / Student Interaction'), ('presentation', 'Presentations / Public Speaking'), ('personal', 'Personal Growth / Confidence'), ('custom', 'Other (User defined)')], default='personal', max_length=50)),
                ('custom_reason', models.CharField(blank=True, help_text="If you select 'Other', write your reason here", max_length=200, null=True)),
                ('time_per_round', models.IntegerField(default=60, help_text='Time in seconds (default 60s, max 180s)')),
                ('num_rounds', models.IntegerField(choices=[(3, '3'), (4, '4'), (5, '5')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200)),
                ('short_description', models.TextField(blank=True, help_text='Optional short description', null=True)),
                ('num_questions', models.IntegerField(choices=[(1, '1'), (5, '5'), (10, '10'), (15, '15'), (20, '20')], default=5)),
                ('time_per_question', models.IntegerField(default=60, help_text='Time per question in seconds (default 60s, max 180s)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dashboard.customquestionset')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('education', models.CharField(max_length=200)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.TextField(help_text='List your key skills, separated by commas')),
                ('experience', models.TextField(blank=True, help_text='Mention work experience or write Fresher', null=True)),
                ('about_you', models.TextField(blank=True, help_text='Briefly describe yourself, your interests and goals', null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('mode', models.CharField(blank=True, choices=[('hr', 'HR'), ('technical', 'Technical'), ('gd', 'Group Discussion')], max_length=20, null=True)),
                ('time_per_question', models.IntegerField(default=60, help_text='Time in seconds (default 60s, max 180s)')),
                ('num_questions', models.IntegerField(choices=[(5, '5'), (10, '10'), (20, '20')], default=5)),
                ('custom_keywords', models.TextField(blank=True, help_text='Optional: Keywords for AI (e.g. DSA, DBMS, Communication)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PresentationPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppt_file', models.FileField(blank=True, null=True, upload_to='presentations/')),
                ('topic_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Write about your topic', null=True)),
                ('audience_type', models.CharField(choices=[('employees', 'Employees'), ('students', 'Students'), ('teachers', 'Teachers'), ('general', 'General Audience')], default='general', max_length=20)),
                ('time_per_question', models.IntegerField(default=60, help_text='Time in seconds (default 60s, max 180s)')),
                ('num_questions', models.IntegerField(choices=[(5, '5'), (10, '10'), (15, '15'), (20, '20')], default=5)),
                ('custom_keywords', models.TextField(blank=True, help_text='Optional: Keywords for AI (e.g. Confidence, Body Language, Communication)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('bio', models.TextField(blank=True, max_length=300, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
